### ISSUE TITLE
CSS changes for different pages

### ISSUE THREAD

**Issue by NickPuljic** [asn10038/AutoIntern-Django#76]
Looks very ugly

**Comment by asn10038** [comment]
### Change popup for a tag label from default alert box to bootstrap popover
https://getbootstrap.com/docs/4.0/components/popovers/

### This can be done by:
* Including popover bootstrap lib
* Include data-toggle, data-content, etc  attributes in the css when the highlight is rendered 
* This should be done in the highlightTags() function in autoInternBase.css

**Comment by asn10038** [comment]
removed see commit 6a0bf0f648a2e4686a63f67dab8452342dbff832
