### ISSUE TITLE
Highlighting within same HTML element raises error

### ISSUE THREAD

**Issue by NickPuljic** [asn10038/AutoIntern-Django#85]

**Comment by asn10038** [comment]
Tried to recreate after changes made to issue #79 but could not recreate experience. Needs testing to determine if this is still an issue.
Please comment here if you can recreate this experience.

**Comment by asn10038** [comment]
Closing this issue tentatively since we can't recreate issue as of : 64f1117b4fd4994d4f33aca485310ab1802508a7

**Comment by asn10038** [comment]
If issue is found please re open

**Comment by asn10038** [comment]
recreated the issue with chrome v 65.x on a mac. Not entirely sure as to what's causing. Still can't recreate on local environment. Needs more testing to determine how to replicate. 

All tags work on the back end. Seems to be front end/javascript problem.
